rate_limits.rate_limit_config.*:
  type: config_entity
  label: 'Rate Limit Config config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    user_flood_route:
      label: 'User Flood Route'
      type: user_flood
    user_flood_global:
      label: 'User Flood Global'
      type: user_flood
    tags:
      type: sequence
      sequence:
        type: string
        label: 'Tag'

user_flood:
  label: 'User Flood'
  type: mapping
  mapping:
    uid_only:
      type: boolean
      label: 'UID only identifier'
    ip_limit:
      type: integer
      label: 'IP limit'
    ip_window:
      type: integer
      label: 'IP window'
    user_limit:
      type: integer
      label: 'User limit'
    user_window:
      type: integer
      label: 'User window'
